// 選擇不同積木選項出現不同的對應選項之規則
// 目的：為了避免使用者亂選做出完全不能用的積木，因此只顯示可用的選項

// 積木類別分群
export const blocklyGroup = [
  'GET_BLOCK_CONTENT',
  'SEND_NAME_INTO_BLOCK',
  'SEND_VALUE_INTO_BLOCK',
  'COMPARE_TWO_BLOCKS_VALUE'
];

export const diveGroup = [
  'GET_DIVE_VALUE_WITH_STATE',
  'SEND_VALUE_INTO_DIVE_WITH_STATE'
];

export const remixGroup = [
  'GET_DIVE_VALUE_WITH_NAME',
  'SEND_DIVE_WITH_STATE_NAME',
  'SEND_DIVE_WITH_BLOCK_VALUE',
  'SEND_DIVE_WITH_NAME_AND_BLOCK_VALUE',
  'GET_STATE_NAME_TO_COMPARE_WITH_DIVE_VALUE',
  'COMPARE_STATE_WITH_DIVE_VALUE'
];

// 元件出現規則
export const isDiveObjectName = [
  'SEND_NAME_INTO_BLOCK',
  'SEND_VALUE_INTO_BLOCK',
  'GET_DIVE_VALUE_WITH_STATE',
  'SEND_VALUE_INTO_DIVE_WITH_STATE',
  'GET_DIVE_VALUE_WITH_NAME',
  'SEND_DIVE_WITH_STATE_NAME',
  'SEND_DIVE_WITH_BLOCK_VALUE',
  'SEND_DIVE_WITH_NAME_AND_BLOCK_VALUE',
  'GET_STATE_NAME_TO_COMPARE_WITH_DIVE_VALUE',
  'COMPARE_STATE_WITH_DIVE_VALUE'
];

export const isDiveObjectAction = [
  'SEND_VALUE_INTO_BLOCK',
  'GET_DIVE_VALUE_WITH_STATE',
  'SEND_VALUE_INTO_DIVE_WITH_STATE',
  'GET_DIVE_VALUE_WITH_NAME',
  'SEND_DIVE_WITH_STATE_NAME',
  'SEND_DIVE_WITH_BLOCK_VALUE',
  'SEND_DIVE_WITH_NAME_AND_BLOCK_VALUE',
  'GET_STATE_NAME_TO_COMPARE_WITH_DIVE_VALUE',
  'COMPARE_STATE_WITH_DIVE_VALUE'
];

export const isDiveLocked = [
  'SEND_VALUE_INTO_DIVE_WITH_STATE',
  'SEND_DIVE_WITH_STATE_NAME',
  'SEND_DIVE_WITH_BLOCK_VALUE',
  'SEND_DIVE_WITH_NAME_AND_BLOCK_VALUE'
];

// 功能篩選規則
export const connectionType = {
  'LEFT_OUTPUT': [
    'GET_BLOCK_CONTENT',
    'SEND_NAME_INTO_BLOCK',
    'SEND_VALUE_INTO_BLOCK',
    'COMPARE_TWO_BLOCKS_VALUE',
    'GET_DIVE_VALUE_WITH_STATE',
    'SEND_VALUE_INTO_DIVE_WITH_STATE',
    'GET_DIVE_VALUE_WITH_NAME',
    'GET_STATE_NAME_TO_COMPARE_WITH_DIVE_VALUE',
    'COMPARE_STATE_WITH_DIVE_VALUE'
  ],
  'OTHER': [
    'GET_BLOCK_CONTENT',
    'SEND_VALUE_INTO_DIVE_WITH_STATE',
    'SEND_DIVE_WITH_STATE_NAME',
    'SEND_DIVE_WITH_BLOCK_VALUE',
    'SEND_DIVE_WITH_NAME_AND_BLOCK_VALUE',
  ]
};

export const portalType = {
  'NONE': [
    'SEND_NAME_INTO_BLOCK',
    'SEND_VALUE_INTO_BLOCK',
    'GET_DIVE_VALUE_WITH_STATE',
    'SEND_VALUE_INTO_DIVE_WITH_STATE',
    'COMPARE_STATE_WITH_DIVE_VALUE'
  ]
};

export const embeddingNumber = {
  'NUM_1': [
    'GET_BLOCK_CONTENT',
    'GET_DIVE_VALUE_WITH_NAME',
    'SEND_DIVE_WITH_STATE_NAME',
    'SEND_DIVE_WITH_BLOCK_VALUE',
    'GET_STATE_NAME_TO_COMPARE_WITH_DIVE_VALUE'
  ],
  'NUM_2': [
    'COMPARE_TWO_BLOCKS_VALUE',
    'SEND_DIVE_WITH_NAME_AND_BLOCK_VALUE',
  ]
};

export const externalType = {
  'TYPE_SINGLE': [
    'GET_BLOCK_CONTENT',
    'GET_DIVE_VALUE_WITH_NAME',
    'SEND_DIVE_WITH_STATE_NAME',
    'SEND_DIVE_WITH_BLOCK_VALUE',
    'GET_STATE_NAME_TO_COMPARE_WITH_DIVE_VALUE'
  ],
  'TYPE_STATEMENT': [
    'GET_BLOCK_CONTENT'
  ]
}

